# Generated by Django 3.2.14 on 2022-10-29 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221029_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='user_group_id',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.groups'),
        ),
    ]
