# Generated by Django 3.2.14 on 2022-10-29 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221029_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.groups'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='id_tovar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.products'),
        ),
    ]
