# Generated by Django 3.2.14 on 2022-10-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20221029_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id_group',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='id_tovar',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_group_id',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
