# Generated by Django 3.2.14 on 2022-10-29 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20221029_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.groups'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='id_tovar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.groups'),
        ),
    ]
