# Generated by Django 3.2.14 on 2022-10-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20221029_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='id_tovar',
            new_name='id_product',
        ),
    ]
