# Generated by Django 3.2.14 on 2022-10-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_id_tovar_reviews_id_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_status',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
