# Generated by Django 3.2.14 on 2022-11-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_users_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='login',
        ),
    ]
