# Generated by Django 3.2.14 on 2022-11-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_username_users_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
